require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

begin
  require 'jasmine'
  load 'jasmine/tasks/jasmine.rake'
rescue LoadError
  task :jasmine do
    abort "Jasmine is not available. In order to run jasmine, you must: (sudo) gem install jasmine"
  end
end

Cucumber::Rake::Task.new(:features) do |task|
  task.cucumber_opts = ["features"]
end