require 'rake'
require 'rake/file_list'

require 'calatrava/configuration'

require 'calatrava/version'
require 'calatrava/apache'
require 'calatrava/app'
require 'calatrava/app_builder'
require 'calatrava/droid_app'
require 'calatrava/ios_app'
require 'calatrava/kernel'
require 'calatrava/manifest'
require 'calatrava/mobile_web_app'
require 'calatrava/project'
require 'calatrava/project_script'
require 'calatrava/resources_build_phase'
require 'calatrava/shell'
require 'calatrava/template'
